{{- if .Values.langfuse.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lang-observatory.fullname" . }}-langfuse
  labels:
    {{- include "lang-observatory.labels" . | nindent 4 }}
    app.kubernetes.io/component: langfuse
spec:
  replicas: {{ .Values.langfuse.replicaCount }}
  selector:
    matchLabels:
      {{- include "lang-observatory.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: langfuse
  template:
    metadata:
      labels:
        {{- include "lang-observatory.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: langfuse
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: langfuse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "lang-observatory.image" (dict "registry" .Values.langfuse.image.registry "repository" .Values.langfuse.image.repository "tag" .Values.langfuse.image.tag "global" .Values.global) }}
          imagePullPolicy: {{ .Values.langfuse.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.langfuse.service.targetPort }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.langfuse.database.existingSecret }}
                  key: database-url
            - name: NEXTAUTH_URL
              value: {{ .Values.langfuse.config.nextauthUrl | quote }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "lang-observatory.fullname" . }}-langfuse-config
                  key: nextauth-secret
            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: {{ include "lang-observatory.fullname" . }}-langfuse-config
                  key: salt
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lang-observatory.fullname" . }}-langfuse-config
                  key: encryption-key
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lang-observatory.fullname" . }}-langfuse-config
                  key: public-key
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lang-observatory.fullname" . }}-langfuse-config
                  key: secret-key
          livenessProbe:
            httpGet:
              path: /api/public/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/public/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.langfuse.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}