{{- if .Values.openlit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lang-observatory.fullname" . }}-openlit
  labels:
    {{- include "lang-observatory.labels" . | nindent 4 }}
    app.kubernetes.io/component: openlit
spec:
  type: {{ .Values.openlit.service.type }}
  ports:
    {{- range .Values.openlit.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "lang-observatory.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: openlit
{{- end }}