apiVersion: v1
kind: Namespace
metadata:
  name: lang-observatory
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: lang-observatory-network-policy
  namespace: lang-observatory
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: lang-observatory
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 9090
  egress:
    - {} # Allow all egress traffic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lang-observatory
  name: lang-observatory-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lang-observatory-rolebinding
  namespace: lang-observatory
subjects:
  - kind: ServiceAccount
    name: lang-observatory
    namespace: lang-observatory
roleRef:
  kind: Role
  name: lang-observatory-role
  apiGroup: rbac.authorization.k8s.io
