name: rerere-audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit-rerere:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git rerere
        run: |
          git config rerere.enabled true
          git config rerere.autoupdate true

      - name: Generate rerere audit
        run: |
          echo "# Rerere Audit Report" > rerere-audit.md
          echo "Generated on: $(date)" >> rerere-audit.md
          echo "" >> rerere-audit.md
          
          if git rerere diff > /dev/null 2>&1; then
            echo "## Recorded Conflict Resolutions" >> rerere-audit.md
            git rerere diff >> rerere-audit.md
          else
            echo "## No recorded conflict resolutions found" >> rerere-audit.md
          fi
          
          echo "" >> rerere-audit.md
          echo "## Rerere Status" >> rerere-audit.md
          git rerere status >> rerere-audit.md || echo "No pending rerere operations" >> rerere-audit.md

      - name: Upload rerere audit
        uses: actions/upload-artifact@v4
        with:
          name: rerere-audit-${{ github.sha }}
          path: rerere-audit.md